apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-secret-sync-events.fullname" . }}
  labels:
    {{- include "vault-secret-sync-events.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vault-secret-sync-events.selectorLabels" . | nindent 4 }}