---
apiVersion: vaultsecretsync.lestak.sh/v1alpha1
kind: VaultSecretSync
metadata:
  name: vault-to-aws-secrets
  namespace: default
spec:
  source:
    address: "https://vault.example.com"
    path: "hello/world"
    namespace: "foo/bar"
  dest:
  - aws:
      name: "example-secret"
      region: "us-west-2"