---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault-secret-sync.configMapName" . }}
  labels:
    {{- include "vault-secret-sync.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- .Values.config | toYaml | nindent 4 }}
