# Default values for vault-secret-sync-events.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

existingConfigMap: ""
config: {}
# # The log level for the application. Can be one of "debug", "info", "warn", "error", "fatal", or "panic".
# logLevel: "info"

# # Configuration for the event server.
# events:
#   # Whether the event server is enabled.
#   enabled: true
#   # The port the event server listens on.
#   port: 8080
#   # Security settings for the event server.
#   security:
#     # Whether security is enabled for the event server.
#     enabled: true
#     # The token used for authentication.
#     token: "your-token"
#     # TLS configuration for the event server.
#     tls: 
#       certFile: "/path/to/certfile"
#       keyFile: "/path/to/keyfile"
#   # Whether to deduplicate events.
#   dedupe: true

# # Configuration for the operator.
# operator:
#   # Whether the operator is enabled.
#   enabled: true
#   # Backend configuration for the operator.
#   workerPoolSize: 10
#   # The number of subscriptions to use.
#   numSubscriptions: 10
#   backend:
#     # The type of backend to use.
#     type: "your-backend-type"
#     # Parameters for the backend.
#     params:
#       param1: "value1"
#       param2: "value2"

# # Configuration for the stores.
# stores:
  # aws:
  #   region: "us-west-2"

  # github:
  #   installId: 12345
  #   appId: 67890
  #   privateKeyPath: "/path/to/private/key"

# # Configuration for the queue.
# queue:
#   # The type of queue to use.
#   type: "your-queue-type"
#   # Parameters for the queue.
#   params:
#     param1: "value1"
#     param2: "value2"

# # Configuration for the metrics server.
# metrics:
#   # The port the metrics server listens on.
#   port: 9090
#   # Security settings for the metrics server.
#   security:
#     # Whether security is enabled for the metrics server.
#     enabled: true
#     # The token used for authentication.
#     token: "your-token"
#     # TLS configuration for the metrics server.
#     tls: 
#       certFile: "/path/to/certfile"
#       keyFile: "/path/to/keyfile"

# notifications:
#   email:
#     enabled: true
#     host: "smtp.example.com"
#     port: 587
#     username: "your-email@example.com"
#     password: "your-email-password"
#     from: "your-email@example.com"
#     to: "recipient@example.com"
#     subject: "Notification Subject"
#     body: "This is the notification body."
#   slack:
#     enabled: true
#     url: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
#     message: "This is the notification message."
#   webhook:
#     enabled: true
#     url: "https://example.com/webhook"
#     method: "POST"
#     headers:
#       Content-Type: "application/json"
#     body: |
#       {
#         "status": "{{ .Status }}",
#         "message": "{{ .Message }}"
#       }



replicaCount: 1

image:
  repository: robertlestak/vault-secret-sync
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

deploymentAnnotations: {}
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

containerPort: 8080

service:
  type: ClusterIP
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env: []
envFrom: []
extraVolumeMounts: []
extraVolumes: []